baseURL = "https://rhgrads.netlify.com/"
languageCode = "en-us"
title = "Red Hat Grads"
theme = "osprey"
publishDir = "docs"
# googleAnalytics = ""
tags = ["red hat", "jobs", "blog", "Graduate", "Intern", "Open Source", "Programming", "Developer"]
config = "config.toml"


[Params]
    tagline = "Life at Red Hat for Graduates and Interns."
    author = "Aidan Cammies"
    description = "A site for recent graduates and interns who want to do great things!"
    logoBig = "/images/rhlogo.png"
    logoSmall = "/images/rhlogo.png"
    favicon = "/images/favicon.ico"
    opengraphImage = "/images/rhlogo.png"
    # twitter = ""
    # linkedin = ""
    # github = "rhgrads"
    facebook = ""
    email = "aidan@redhat.com"
    googleTagManager = ""
    highlightJS = true
    copyright = false
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false
    addThis = "ra-5b5b2fb443af7dfd"


[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Posts"
    url  = "/#posts"
    weight = 2
[[menu.main]]
    name = "Jobs"
    url  = "/#jobs"
    weight = 3
[[menu.main]]
    name = "Admin"
    url  = "/admin"
    weight = 4
# [[menu.main]]
#     name = "Gallery"
#     url  = "/#work"
#     weight = 5
